name: Chimmy Apple Music

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
          libcairo2-dev \
          libpango1.0-dev \
          libjpeg-dev \
          libgif-dev \
          librsvg2-dev

      - run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
